/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "eejyopdmasozizdxxvrq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlanlvcGRtYXNveml6ZHh4dnJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ2MDg0MjksImV4cCI6MjEwMDE4NDQyOX0.NUjOchgq5YsgkMAatTa3COS-x-fIlqu1P7iSkEmBJec"